---

##
# Chooses the right bootloader tasks or delete the packages
##

- name: Check if systemd-boot is used
  ansible.builtin.stat:
    path: /boot/efi/EFI/systemd
  register: systemd_boot

- name: Include systemd-boot configuration tasks
  ansible.builtin.include_tasks: systemd.yml
  when: systemd_boot.stat.exists

- name: Check if GRUB is used
  ansible.builtin.stat:
    path: /etc/default/grub
  register: grub_config

- name: Include GRUB configuration tasks
  ansible.builtin.include_tasks: grub.yml
  when: grub_config.stat.exists

- name: Delete KVM Because of Failures
  when: not systemd_boot.stat.exists and not grub_config.stat.exists
  block:
  - name: Warn if no supported bootloader was detected
    ansible.builtin.fail:
      msg: "Warning: Neither systemd-boot nor GRUB was detected. IOMMU configuration was not applied. KVM will be removed..."
