---
##
# Configures grub menu entry and handles GPU.
##

- name: Create GRUB iommu.cfg configuration file
  ansible.builtin.copy:
    dest: /etc/default/grub.d/iommu.cfg
    content: |
      # IOMMU configuration added by Ansible
      GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT {{ iommu_param }}"
    mode: "0644"
  register: grub_updated

- name: Create GRUB config directory for GPU passthrough
  when: kvm_gpu_passthrough == 'bootbased'
  ansible.builtin.file:
    path: /etc/grub.d/60_gpu_passthrough
    state: directory
    mode: "0755"

- name: Create custom GRUB entries for each GPU group
  ansible.builtin.template:
    src: gpu_passthrough_entry.j2
    dest: "/etc/grub.d/60_gpu_passthrough/gpu{{ gpu_group_el[2] }}"
    mode: "0755"
  loop: "{{ gpus_passthrough }}"
  when: kvm_gpu_passthrough == 'bootbased'
  loop_control:
    loop_var: gpu_group_el # ['group_id', 'vendor', 'vga_id,audio_id']

- name: Update GRUB
  ansible.builtin.command: update-grub
  changed_when: false
