---

# Verification

- name: Check for hardware virtualization support
  become: true
  ansible.builtin.shell: dmesg | grep -E -i "(VT-d|AMD-Vi)"
  register: virt_check
  changed_when: false
  failed_when: false
  check_mode: false

- name: Verify virtualization is enabled
  ansible.builtin.assert:
    that: virt_check.rc == 0
    fail_msg: "Hardware virtualization (Intel VT-d or AMD-Vi) is not enabled in BIOS/UEFI"
    success_msg: "Hardware virtualization is enabled"

- name: Set IOMMU parameter based on CPU vendor
  ansible.builtin.set_fact:
    iommu_param: >-
      {{ 'intel_iommu=on' if 'Intel' in ansible_processor[0] else 'amd_iommu=on' }}

# Installation
- name: Install KVM and virtualization packages
  become: true
  ansible.builtin.apt:
    name:
      - qemu-kvm                # KVM hypervisor
      - qemu-utils              # QEMU utilities (e.g., qemu-img)
      - libvirt-daemon-system   # libvirt system background service
      - libvirt-clients         # libvirt client utilities
      - bridge-utils            # network bridging utilities
      - virt-manager            # GUI wrapper
      - ovmf                    # Enables custom UEFIs in VMs
    state: present
    update_cache: true
  notify: Verify KVM installation

# GPU Passthrough Configuration (must run before bootloader)
- name: Include GPU passthrough tasks
  ansible.builtin.include_tasks: passthrough.yml
  when: kvm_gpu_passthrough in ['bootbased', 'runtime']

# Configure Bootloader
- name: Configure bootloader
  ansible.builtin.import_tasks: bootloader.yml

# User Configuration
- name: Add current user to libvirt groups
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - libvirt
      - kvm
    append: true
