---
- name: Install Python packages
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - python3-dev
      - python3-pip
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_time | default(3600) }}"
