---
- name: Install Flatpak package
  become: true
  ansible.builtin.apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_time | default(3600) }}"

- name: Add the flathub flatpak repository remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
