---
- name: Add git PPA
  become: true
  ansible.builtin.deb822_repository:
    name: "git-core-ubuntu-ppa-{{ ansible_distribution_release }}"
    types: deb
    uris: "https://ppa.launchpadcontent.net/git-core/ppa/ubuntu/"
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF911AB184317630C59970973E363C90F8F1B6217

- name: Install git
  become: true
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true

- name: Install tig
  become: true
  ansible.builtin.apt:
    name: tig
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_time | default(3600) }}"

- name: Check if .gitconfig exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.gitconfig"
  register: gitconfig_stat

- name: Copy .gitconfig only if it does not exist
  ansible.builtin.copy:
    src: gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: "0644"
  when: not gitconfig_stat.stat.exists
