---
- name: Add Edge repository
  become: true
  ansible.builtin.deb822_repository:
    name: microsoft-edge
    types: deb
    uris: https://packages.microsoft.com/repos/edge
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://packages.microsoft.com/keys/microsoft.asc

- name: Install Edge
  become: true
  ansible.builtin.apt:
    name: microsoft-edge-stable
    state: present
    update_cache: true
