name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - release
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      ## Install dependencies
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible and Tools
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core ansible-lint
          ansible-galaxy collection install -r requirements.yml

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Install Prettier
        run: npm install --global prettier

      ## Actual tasks
      - name: Lint
        run: make check
