name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - release
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      ## Install dependencies
      - name: Install ShellCheck, Ansible, and Ansible Lint
        run: |
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible ansible-lint python3-apt shellcheck
          ansible-galaxy collection install -r requirements.yml

      - name: Install Prettier
        run: npm install --global prettier

      ## Actual tasks
      - name: Lint
        run: make check
