name: Ubuntu test

on:
  push:
    branches:
      - master
      - release
    paths-ignore:
      - "**/*.md"
  schedule:
    - cron: "0 4 * * 6" # Runs every Saturday at 4:00 AM
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test-default-packages:
    name: Test default set of packages
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    env:
      TERM: dumb

    steps:
      - name: Change APT mirror to archive.ubuntu.com to avoid 404 Not Found error
        run: |
          # Remove the existing ubuntu.sources file
          sudo rm -f /etc/apt/sources.list.d/ubuntu.sources

          # Download the new ubuntu.sources file from the specific commit
          sudo curl -o /etc/apt/sources.list.d/ubuntu.sources \
            "https://raw.githubusercontent.com/leinardi/JDInstaller/$GITHUB_SHA/.github/ubuntu.sources"

          # Update package lists
          sudo apt-get update

      - name: Setup Ubuntu desktop minimal
        run: |
          sudo apt-get install -y ubuntu-desktop-minimal

      - name: Reproduce install instructions from README.md
        run: |
          sudo apt install git make
          git clone --no-checkout https://github.com/leinardi/JDInstaller.git
          cd JDInstaller
          git fetch origin $GITHUB_SHA
          git checkout $GITHUB_SHA
          make install

  test-all-packages-besides-davinci:
    name: Test all packages besides DaVinci Resolve
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    env:
      TERM: dumb

    steps:
      - name: Change APT mirror to archive.ubuntu.com to avoid 404 Not Found error
        run: |
          # Remove the existing ubuntu.sources file
          sudo rm -f /etc/apt/sources.list.d/ubuntu.sources

          # Download the new ubuntu.sources file from the specific commit
          sudo curl -o /etc/apt/sources.list.d/ubuntu.sources \
            "https://raw.githubusercontent.com/leinardi/JDInstaller/$GITHUB_SHA/.github/ubuntu.sources"

          # Update package lists
          sudo apt-get update

      - name: Setup Ubuntu desktop minimal
        run: |
          sudo apt-get install -y ubuntu-desktop-minimal

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ansible from PPA
        run: |
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible
          ansible-galaxy collection install -r requirements.yml

      - name: Enable all disabled packages except DaVinci Resolve
        run: |
          sed -i '/davinci_resolve_enabled: false/!s/_enabled: false/_enabled: true/' group_vars/all.yml

      - name: Run playbook
        run: ansible-playbook ubuntu-setup.yml -vvv
